"""Add matching system fields

Revision ID: 20e2b34184a8
Revises: 
Create Date: 2026-02-11 06:36:38.503357

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '20e2b34184a8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('interests', sa.JSON(), nullable=True),
    sa.Column('travel_style', sa.String(length=50), nullable=True),
    sa.Column('travel_pace', sa.String(length=20), nullable=True),
    sa.Column('preferred_destinations', sa.JSON(), nullable=True),
    sa.Column('budget_min', sa.Float(), nullable=True),
    sa.Column('budget_max', sa.Float(), nullable=True),
    sa.Column('accessibility_needs', sa.JSON(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('safety_score', sa.Float(), nullable=True),
    sa.Column('interest_embedding', sa.JSON(), nullable=True),
    sa.Column('last_match_update', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('travel_spaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('itinerary_id', sa.Integer(), nullable=True),
    sa.Column('min_members', sa.Integer(), nullable=False),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('current_members', sa.Integer(), nullable=False),
    sa.Column('voting_threshold', sa.Float(), nullable=False),
    sa.Column('require_verification', sa.Boolean(), nullable=False),
    sa.Column('women_only', sa.Boolean(), nullable=False),
    sa.Column('min_age', sa.Integer(), nullable=False),
    sa.Column('max_age', sa.Integer(), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('interests', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('FORMING', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='travelspacestatus'), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travel_spaces_creator_id'), 'travel_spaces', ['creator_id'], unique=False)
    op.create_index(op.f('ix_travel_spaces_id'), 'travel_spaces', ['id'], unique=False)
    op.create_table('travel_space_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('application_message', sa.Text(), nullable=True),
    sa.Column('compatibility_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'ACTIVE', 'LEFT', name='membershipstatus'), nullable=False),
    sa.Column('votes_for', sa.Integer(), nullable=False),
    sa.Column('votes_against', sa.Integer(), nullable=False),
    sa.Column('votes_needed', sa.Integer(), nullable=True),
    sa.Column('is_creator', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['space_id'], ['travel_spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travel_space_memberships_id'), 'travel_space_memberships', ['id'], unique=False)
    op.create_index(op.f('ix_travel_space_memberships_user_id'), 'travel_space_memberships', ['user_id'], unique=False)
    op.create_table('membership_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('membership_id', sa.Integer(), nullable=False),
    sa.Column('voter_id', sa.Integer(), nullable=False),
    sa.Column('vote', sa.Enum('APPROVE', 'REJECT', 'ABSTAIN', name='votetype'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['travel_space_memberships.id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['travel_spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_membership_votes_id'), 'membership_votes', ['id'], unique=False)
    op.create_index(op.f('ix_membership_votes_voter_id'), 'membership_votes', ['voter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_membership_votes_voter_id'), table_name='membership_votes')
    op.drop_index(op.f('ix_membership_votes_id'), table_name='membership_votes')
    op.drop_table('membership_votes')
    op.drop_index(op.f('ix_travel_space_memberships_user_id'), table_name='travel_space_memberships')
    op.drop_index(op.f('ix_travel_space_memberships_id'), table_name='travel_space_memberships')
    op.drop_table('travel_space_memberships')
    op.drop_index(op.f('ix_travel_spaces_id'), table_name='travel_spaces')
    op.drop_index(op.f('ix_travel_spaces_creator_id'), table_name='travel_spaces')
    op.drop_table('travel_spaces')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
